# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinfo',
            name='ipaddr',
            field=models.CharField(default='0.0.0.0', max_length=16),
            preserve_default=False,
        ),
    ]
