# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-18 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_portal', '0003_numberinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='nodogsplash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipAddr', models.CharField(max_length=16)),
                ('macAddr', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=10)),
                ('redir', models.CharField(max_length=100)),
            ],
        ),
    ]
